- name: Add grafana key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana
    state: latest

- name: start grafana
  service:
      name: grafana-server
      state: started
      enabled: yes
- name: grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana
