- name: Add grafana key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana
    state: latest
  notify: Change pass

- name: start grafana
  service:
      name: grafana-server
      state: started
      enabled: yes

- name: Create directory /var/lib/grafana/dashboards
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: grafana datasource
  template:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana
  tags: ds

- name: grafana dashboard
  template:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana

- name: grafana dashboard upload
  copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify: Restart grafana

- name: grafana dashboard 2 upload
  copy:
    src: syslog.json
    dest: /var/lib/grafana/dashboards/syslog.json
  notify: Restart grafana
  tags: dh


- name: grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana
