- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    container_default_behavior: no_defaults
    restart_policy: always

- name: Create directories
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
  loop:
  - dashboards
  - datasources

- name: Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes

- name: Fill dashboards directory
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/
  notify: Restart grafana
  loop:
  - main.json
  - sql.json
  - syslog.json

- name: Fill dashboards directory
  template:
    src: dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/
  notify: Restart grafana

- name: Fill datasources directory
  template:
    src: datasource.yaml
    dest: /opt/grafana/provisioning/datasources/
  notify: Restart grafana
