- name: reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and reload daemon
  systemd:
    name: pinger
    daemon_reload: yes
    enabled: yes
    state: started

- name: restart pinger
  ansible.builtin.service:
    name: pinger
    state: restarted
