- name: Create directories
  ansible.builtin.file:
    path: "/opt/agama"
    state: directory

- name: Download agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Agama building
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Agama Docker container
  community.docker.docker_container:
    name: agama{{ item }}
    image: agama
    published_ports: "800{{ item }}:8000"
    container_default_behavior: no_defaults
    env:
      AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@mysql2/{{ mysql_database }}
    restart_policy: always
  loop:
    - 1
    - 2