- name: Add user backup
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: server key config
  template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    mode: '0644'
    force: no

- name: Create directory restore
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0755'

- name: Install duplicity
  apt:
    name: duplicity
    state: latest
    update_cache: yes
