- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart nginxexporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted
