- name: Install sql exporter
  apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: sql exporter start
  service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes

- name: Exporter User
  community.mysql.mysql_user:
    name: "exporter"          
    password: "{{ mysql_exporter_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: 
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
  notify: Restart sql

- name: MySQL exporter config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: '0400'
    owner: prometheus
  notify: 
    - Restart sql
    - Restart mysqlexporter
