- name: Restart mysqlexporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Restart sql
  ansible.builtin.service:
    name: mysql
    state: restarted
