- name: Turn off systemd
  service:
      name: systemd-resolved
      state: stopped
      enabled: no

- name: resolv.conf
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf

