- name: Install bind exporter
  apt:
    name: prometheus-bind-exporter
    state: latest

- name: bind exporter start
  service:
      name: prometheus-bind-exporter
      state: started
      enabled: yes

