- name: Install nginx exporter
  apt:
    name: prometheus-nginx-exporter
    state: latest

- name: nginx exporter start
  service:
      name: prometheus-nginx-exporter
      state: started
      enabled: yes

- name: Nginx config
  template:
    src: exporter
    dest: /etc/nginx/sites-enabled/exporter
  notify:
     - Restart nginx
     - Restart nginxexporter
